### ISSUE TITLE
The different between HIERMATCH-cifar-100 and HIERMATCH-cifar-100-partial

### ISSUE THREAD

**Issue by JiahangWu** [07Agarg/HIERMATCH#1]
Hi Ashima! I don't understand what different between HIERMATCH-cifar-100 and HIERMATCH-cifar-100-partial. Is HIERMATCH-cifar-100 doesn't  use coarse class labels as a weak supervisory signal? Can you explan it? Thank you!

**Comment by 07Agarg** [comment]
Hi, 

HIERMATCH-cifar-100 is used for experiments with setting (10k, 0, 0) or (10k, 0, -) i.e. when no additional coarse level samples are not used. HIERMATCH-cifar-100-partial is used for experiments with setting (8k, 2k, 0) etc. 

Thanks,
